usingSystem;
usingstaticSystem.Console;
classCountVowelsModularized
{
	publicstaticvoidMain()
	{
		stringphrase=ReadLine();
		intvowel=CountVowels(phrase);
		WriteLine(vowel);
	}
	publicstaticintCountVowels(stringinputString)
	{
		intvowel=0;
		intcons=0;
		intlen=inputString.Length;
		for(inti=0;i<len;i++)
		{
			if(inputString[i]=='a'||inputString[i]=='e'||inputString[i]=='i'||inputString[i]=='o'||inputString[i]=='u'||inputString[i]=='A'||inputString[i]=='E'||inputString[i]=='I'||inputString[i]=='O'||inputString[i]=='U')
			{
				vowel++;
			}
			elseif((inputString[i]>='a'&&inputString[i]<='z')||(inputString[i]>='A'&&inputString[i]<='Z'))
			{
				cons++;
			}
		}
		returnvowel;
	}
}
